export interface ThemeColors {
  "--page-bg-color": string;
  "--controls-bg-color": string;
  "--input-bg-color": string;
  "--input-border-color": string;
  "--input-text-color": string;
  "--button-primary-bg-color": string;
  "--button-primary-hover-bg-color": string;
  "--thumbnail-bg-color": string;
  "--thumbnail-grid-color": string;
  "--thumbnail-main-text-color": string;
  "--thumbnail-secondary-text-color": string;
}

export interface Theme {
  name: string;
  category: string;
  colors: ThemeColors;
}

export const themes: Record<string, Theme> = {
  "default": {
    name: "Default",
    category: "Dark",
    colors: {
      "--page-bg-color": "#10121a",
      "--controls-bg-color": "#222533",
      "--input-bg-color": "#2a2c3a",
      "--input-border-color": "#2a2c3a",
      "--input-text-color": "#ffffff",
      "--button-primary-bg-color": "#3b3e52",
      "--button-primary-hover-bg-color": "#4c4f69",
      "--thumbnail-bg-color": "#10131C",
      "--thumbnail-grid-color": "rgba(255, 255, 255, 0.05)",
      "--thumbnail-main-text-color": "#ffffff",
      "--thumbnail-secondary-text-color": "#a9b1d6",
    },
  },
  "midnight-blue": {
    name: "Midnight Blue",
    category: "Dark",
    colors: {
      "--page-bg-color": "#0a0f1d",
      "--controls-bg-color": "#101830",
      "--input-bg-color": "#1c2849",
      "--input-border-color": "#1c2849",
      "--input-text-color": "#e0eafc",
      "--button-primary-bg-color": "#364e8f",
      "--button-primary-hover-bg-color": "#4a6ac2",
      "--thumbnail-bg-color": "#0c142d",
      "--thumbnail-grid-color": "rgba(173, 216, 230, 0.1)",
      "--thumbnail-main-text-color": "#e0eafc",
      "--thumbnail-secondary-text-color": "#8a9fcf",
    },
  },
  "matrix-green": {
    name: "Matrix Green",
    category: "Colorful",
    colors: {
      "--page-bg-color": "#050a05",
      "--controls-bg-color": "#0a140a",
      "--input-bg-color": "#0f200f",
      "--input-border-color": "#0f200f",
      "--input-text-color": "#33ff33",
      "--button-primary-bg-color": "#006400",
      "--button-primary-hover-bg-color": "#008000",
      "--thumbnail-bg-color": "#0d130d",
      "--thumbnail-grid-color": "rgba(0, 255, 0, 0.15)",
      "--thumbnail-main-text-color": "#33ff33",
      "--thumbnail-secondary-text-color": "#00cc00",
    },
  },
  "crimson-red": {
    name: "Crimson Red",
    category: "Colorful",
    colors: {
      "--page-bg-color": "#1f0d0d",
      "--controls-bg-color": "#2b1212",
      "--input-bg-color": "#401a1a",
      "--input-border-color": "#401a1a",
      "--input-text-color": "#ffcdd2",
      "--button-primary-bg-color": "#a02c2c",
      "--button-primary-hover-bg-color": "#bf3636",
      "--thumbnail-bg-color": "#1a0a0a",
      "--thumbnail-grid-color": "rgba(220, 20, 60, 0.15)",
      "--thumbnail-main-text-color": "#ffcdd2",
      "--thumbnail-secondary-text-color": "#dc143c",
    },
  },
  "sunset-orange": {
    name: "Sunset Orange",
    category: "Colorful",
    colors: {
      "--page-bg-color": "#2a1a05",
      "--controls-bg-color": "#3f280a",
      "--input-bg-color": "#5c3a0f",
      "--input-border-color": "#5c3a0f",
      "--input-text-color": "#ffd700",
      "--button-primary-bg-color": "#b87900",
      "--button-primary-hover-bg-color": "#e09400",
      "--thumbnail-bg-color": "#2a1a0a",
      "--thumbnail-grid-color": "rgba(255, 165, 0, 0.1)",
      "--thumbnail-main-text-color": "#ffd700",
      "--thumbnail-secondary-text-color": "#ffa500",
    },
  },
  "arctic-light": {
    name: "Arctic Light",
    category: "Light",
    colors: {
      "--page-bg-color": "#757575",
      "--controls-bg-color": "#ffffff",
      "--input-bg-color": "#f0f4f8",
      "--input-border-color": "#d1d9e6",
      "--input-text-color": "#24292e",
      "--button-primary-bg-color": "#4a7cf7",
      "--button-primary-hover-bg-color": "#6c95f9",
      "--thumbnail-bg-color": "#f0f4f8",
      "--thumbnail-grid-color": "rgba(0, 0, 0, 0.07)",
      "--thumbnail-main-text-color": "#24292e",
      "--thumbnail-secondary-text-color": "#586069",
    },
  },
  "slate-gray": {
    name: "Slate Gray",
    category: "Dark",
    colors: {
      "--page-bg-color": "#2d3748",
      "--controls-bg-color": "#4a5568",
      "--input-bg-color": "#718096",
      "--input-border-color": "#718096",
      "--input-text-color": "#ffffff",
      "--button-primary-bg-color": "#2d3748",
      "--button-primary-hover-bg-color": "#1a202c",
      "--thumbnail-bg-color": "#1a202c",
      "--thumbnail-grid-color": "rgba(255, 255, 255, 0.06)",
      "--thumbnail-main-text-color": "#e2e8f0",
      "--thumbnail-secondary-text-color": "#a0aec0",
    },
  },
  "charcoal": {
    name: "Charcoal",
    category: "Dark",
    colors: {
      "--page-bg-color": "#232B2B",
      "--controls-bg-color": "#36454F",
      "--input-bg-color": "#414a4c",
      "--input-border-color": "#505a5f",
      "--input-text-color": "#f5f5f5",
      "--button-primary-bg-color": "#5A5A5A",
      "--button-primary-hover-bg-color": "#696969",
      "--thumbnail-bg-color": "#202020",
      "--thumbnail-grid-color": "rgba(255, 255, 255, 0.05)",
      "--thumbnail-main-text-color": "#ffffff",
      "--thumbnail-secondary-text-color": "#c0c0c0",
    },
  },
  "cyberpunk-neon": {
    name: "Cyberpunk Neon",
    category: "Colorful",
    colors: {
      "--page-bg-color": "#0a0a0f",
      "--controls-bg-color": "#1a1a2e",
      "--input-bg-color": "#16213e",
      "--input-border-color": "#0f3460",
      "--input-text-color": "#00ffff",
      "--button-primary-bg-color": "#e94560",
      "--button-primary-hover-bg-color": "#ff6b8a",
      "--thumbnail-bg-color": "#0f0f23",
      "--thumbnail-grid-color": "rgba(0, 255, 255, 0.1)",
      "--thumbnail-main-text-color": "#00ffff",
      "--thumbnail-secondary-text-color": "#ff00ff",
    },
  },
  "synthwave-purple": {
    name: "Synthwave Purple",
    category: "Colorful",
    colors: {
      "--page-bg-color": "#1a0d26",
      "--controls-bg-color": "#2d1b3d",
      "--input-bg-color": "#3d2352",
      "--input-border-color": "#4a2c5a",
      "--input-text-color": "#f0c0ff",
      "--button-primary-bg-color": "#8b5cf6",
      "--button-primary-hover-bg-color": "#a78bfa",
      "--thumbnail-bg-color": "#1f1129",
      "--thumbnail-grid-color": "rgba(139, 92, 246, 0.15)",
      "--thumbnail-main-text-color": "#f0c0ff",
      "--thumbnail-secondary-text-color": "#c084fc",
    },
  },
  "forest-green": {
    name: "Forest Green",
    category: "Colorful",
    colors: {
      "--page-bg-color": "#0d1b0d",
      "--controls-bg-color": "#1a2e1a",
      "--input-bg-color": "#2d4a2d",
      "--input-border-color": "#3d5a3d",
      "--input-text-color": "#90ee90",
      "--button-primary-bg-color": "#228b22",
      "--button-primary-hover-bg-color": "#32cd32",
      "--thumbnail-bg-color": "#0f1f0f",
      "--thumbnail-grid-color": "rgba(34, 139, 34, 0.1)",
      "--thumbnail-main-text-color": "#90ee90",
      "--thumbnail-secondary-text-color": "#7cfc00",
    },
  },
  "ocean-blue": {
    name: "Ocean Blue",
    category: "Colorful",
    colors: {
      "--page-bg-color": "#0c1821",
      "--controls-bg-color": "#1e3a5f",
      "--input-bg-color": "#2a4d6b",
      "--input-border-color": "#3d6b8c",
      "--input-text-color": "#87ceeb",
      "--button-primary-bg-color": "#4682b4",
      "--button-primary-hover-bg-color": "#5f9ea0",
      "--thumbnail-bg-color": "#0f1f2a",
      "--thumbnail-grid-color": "rgba(70, 130, 180, 0.1)",
      "--thumbnail-main-text-color": "#87ceeb",
      "--thumbnail-secondary-text-color": "#4682b4",
    },
  },
  "rose-gold": {
    name: "Rose Gold",
    category: "Colorful",
    colors: {
      "--page-bg-color": "#2a1a1f",
      "--controls-bg-color": "#3d2832",
      "--input-bg-color": "#4a3240",
      "--input-border-color": "#5a3d4f",
      "--input-text-color": "#f4c2c2",
      "--button-primary-bg-color": "#cd919e",
      "--button-primary-hover-bg-color": "#e6a8b7",
      "--thumbnail-bg-color": "#2d1d25",
      "--thumbnail-grid-color": "rgba(205, 145, 158, 0.1)",
      "--thumbnail-main-text-color": "#f4c2c2",
      "--thumbnail-secondary-text-color": "#cd919e",
    },
  },
  "mint-fresh": {
    name: "Mint Fresh",
    category: "Colorful",
    colors: {
      "--page-bg-color": "#0f1f1a",
      "--controls-bg-color": "#1a332a",
      "--input-bg-color": "#2a4d3d",
      "--input-border-color": "#3d6650",
      "--input-text-color": "#98fb98",
      "--button-primary-bg-color": "#20b2aa",
      "--button-primary-hover-bg-color": "#40e0d0",
      "--thumbnail-bg-color": "#12241e",
      "--thumbnail-grid-color": "rgba(32, 178, 170, 0.1)",
      "--thumbnail-main-text-color": "#98fb98",
      "--thumbnail-secondary-text-color": "#20b2aa",
    },
  },
  "cosmic-purple": {
    name: "Cosmic Purple",
    category: "Colorful",
    colors: {
      "--page-bg-color": "#0b0b1f",
      "--controls-bg-color": "#1a1a3a",
      "--input-bg-color": "#2d2d5a",
      "--input-border-color": "#3d3d6b",
      "--input-text-color": "#dda0dd",
      "--button-primary-bg-color": "#6a5acd",
      "--button-primary-hover-bg-color": "#8470ff",
      "--thumbnail-bg-color": "#0f0f2a",
      "--thumbnail-grid-color": "rgba(106, 90, 205, 0.15)",
      "--thumbnail-main-text-color": "#dda0dd",
      "--thumbnail-secondary-text-color": "#9370db",
    },
  },
  "amber-glow": {
    name: "Amber Glow",
    category: "Colorful",
    colors: {
      "--page-bg-color": "#1f1a0d",
      "--controls-bg-color": "#332a1a",
      "--input-bg-color": "#4d3d2a",
      "--input-border-color": "#66503d",
      "--input-text-color": "#ffd700",
      "--button-primary-bg-color": "#ff8c00",
      "--button-primary-hover-bg-color": "#ffa500",
      "--thumbnail-bg-color": "#241e12",
      "--thumbnail-grid-color": "rgba(255, 140, 0, 0.1)",
      "--thumbnail-main-text-color": "#ffd700",
      "--thumbnail-secondary-text-color": "#ff8c00",
    },
  },
  "ice-blue": {
    name: "Ice Blue",
    category: "Colorful",
    colors: {
      "--page-bg-color": "#0d1a1f",
      "--controls-bg-color": "#1a2d33",
      "--input-bg-color": "#2a404d",
      "--input-border-color": "#3d5366",
      "--input-text-color": "#b0e0e6",
      "--button-primary-bg-color": "#4169e1",
      "--button-primary-hover-bg-color": "#6495ed",
      "--thumbnail-bg-color": "#0f1e24",
      "--thumbnail-grid-color": "rgba(65, 105, 225, 0.1)",
      "--thumbnail-main-text-color": "#b0e0e6",
      "--thumbnail-secondary-text-color": "#87ceeb",
    },
  },
  "volcanic-red": {
    name: "Volcanic Red",
    category: "Colorful",
    colors: {
      "--page-bg-color": "#1f0a0a",
      "--controls-bg-color": "#331a1a",
      "--input-bg-color": "#4d2a2a",
      "--input-border-color": "#663d3d",
      "--input-text-color": "#ff6b6b",
      "--button-primary-bg-color": "#dc143c",
      "--button-primary-hover-bg-color": "#ff1744",
      "--thumbnail-bg-color": "#240f0f",
      "--thumbnail-grid-color": "rgba(255, 107, 107, 0.1)",
      "--thumbnail-main-text-color": "#ff6b6b",
      "--thumbnail-secondary-text-color": "#ff4757",
    },
  },
  "neon-lime": {
    name: "Neon Lime",
    category: "Colorful",
    colors: {
      "--page-bg-color": "#0a1f0a",
      "--controls-bg-color": "#1a331a",
      "--input-bg-color": "#2a4d2a",
      "--input-border-color": "#3d663d",
      "--input-text-color": "#32ff32",
      "--button-primary-bg-color": "#00ff00",
      "--button-primary-hover-bg-color": "#39ff14",
      "--thumbnail-bg-color": "#0f240f",
      "--thumbnail-grid-color": "rgba(0, 255, 0, 0.15)",
      "--thumbnail-main-text-color": "#32ff32",
      "--thumbnail-secondary-text-color": "#00ff00",
    },
  },
  "deep-space": {
    name: "Deep Space",
    category: "Dark",
    colors: {
      "--page-bg-color": "#0a0a1a",
      "--controls-bg-color": "#1a1a2e",
      "--input-bg-color": "#2a2a4d",
      "--input-border-color": "#3d3d66",
      "--input-text-color": "#c9c9ff",
      "--button-primary-bg-color": "#4b0082",
      "--button-primary-hover-bg-color": "#6a0dad",
      "--thumbnail-bg-color": "#0f0f24",
      "--thumbnail-grid-color": "rgba(75, 0, 130, 0.15)",
      "--thumbnail-main-text-color": "#c9c9ff",
      "--thumbnail-secondary-text-color": "#9370db",
    },
  },
  "golden-hour": {
    name: "Golden Hour",
    category: "Colorful",
    colors: {
      "--page-bg-color": "#2a1f0d",
      "--controls-bg-color": "#3d2f1a",
      "--input-bg-color": "#4d3f2a",
      "--input-border-color": "#66523d",
      "--input-text-color": "#ffeaa7",
      "--button-primary-bg-color": "#fdcb6e",
      "--button-primary-hover-bg-color": "#f39c12",
      "--thumbnail-bg-color": "#2d2412",
      "--thumbnail-grid-color": "rgba(253, 203, 110, 0.1)",
      "--thumbnail-main-text-color": "#ffeaa7",
      "--thumbnail-secondary-text-color": "#fdcb6e",
    },
  },
  "obsidian-dark": {
    name: "Obsidian Dark",
    category: "Dark",
    colors: {
      "--page-bg-color": "#0d0d0d",
      "--controls-bg-color": "#1d1d1d",
      "--input-bg-color": "#2d2d2d",
      "--input-border-color": "#3d3d3d",
      "--input-text-color": "#e8e8e8",
      "--button-primary-bg-color": "#4a4a4a",
      "--button-primary-hover-bg-color": "#5a5a5a",
      "--thumbnail-bg-color": "#0f0f0f",
      "--thumbnail-grid-color": "rgba(255, 255, 255, 0.03)",
      "--thumbnail-main-text-color": "#ffffff",
      "--thumbnail-secondary-text-color": "#a0a0a0",
    },
  },
  "void-black": {
    name: "Void Black",
    category: "Dark",
    colors: {
      "--page-bg-color": "#000000",
      "--controls-bg-color": "#0a0a0a",
      "--input-bg-color": "#1a1a1a",
      "--input-border-color": "#2a2a2a",
      "--input-text-color": "#f0f0f0",
      "--button-primary-bg-color": "#333333",
      "--button-primary-hover-bg-color": "#444444",
      "--thumbnail-bg-color": "#050505",
      "--thumbnail-grid-color": "rgba(255, 255, 255, 0.02)",
      "--thumbnail-main-text-color": "#ffffff",
      "--thumbnail-secondary-text-color": "#888888",
    },
  },
  "midnight-void": {
    name: "Midnight Void",
    category: "Dark",
    colors: {
      "--page-bg-color": "#050510",
      "--controls-bg-color": "#0a0a1a",
      "--input-bg-color": "#1a1a2a",
      "--input-border-color": "#2a2a3a",
      "--input-text-color": "#e0e0f0",
      "--button-primary-bg-color": "#3a3a4a",
      "--button-primary-hover-bg-color": "#4a4a5a",
      "--thumbnail-bg-color": "#0a0a15",
      "--thumbnail-grid-color": "rgba(255, 255, 255, 0.03)",
      "--thumbnail-main-text-color": "#ffffff",
      "--thumbnail-secondary-text-color": "#a0a0b0",
    },
  },
  "lavender-dream": {
    name: "Lavender Dream",
    category: "Colorful",
    colors: {
      "--page-bg-color": "#1a0f2e",
      "--controls-bg-color": "#2d1f4a",
      "--input-bg-color": "#3d2a5a",
      "--input-border-color": "#4d356a",
      "--input-text-color": "#e6e6fa",
      "--button-primary-bg-color": "#9370db",
      "--button-primary-hover-bg-color": "#b19cd9",
      "--thumbnail-bg-color": "#1f1435",
      "--thumbnail-grid-color": "rgba(147, 112, 219, 0.12)",
      "--thumbnail-main-text-color": "#e6e6fa",
      "--thumbnail-secondary-text-color": "#d8bfd8",
    },
  },
  "emerald-forest": {
    name: "Emerald Forest",
    category: "Colorful",
    colors: {
      "--page-bg-color": "#0d2e0d",
      "--controls-bg-color": "#1a4d1a",
      "--input-bg-color": "#2a6b2a",
      "--input-border-color": "#3a8a3a",
      "--input-text-color": "#98fb98",
      "--button-primary-bg-color": "#228b22",
      "--button-primary-hover-bg-color": "#32cd32",
      "--thumbnail-bg-color": "#0f3a0f",
      "--thumbnail-grid-color": "rgba(34, 139, 34, 0.12)",
      "--thumbnail-main-text-color": "#98fb98",
      "--thumbnail-secondary-text-color": "#90ee90",
    },
  },
  "sapphire-night": {
    name: "Sapphire Night",
    category: "Colorful",
    colors: {
      "--page-bg-color": "#0a1a2e",
      "--controls-bg-color": "#1a2a4a",
      "--input-bg-color": "#2a3a6a",
      "--input-border-color": "#3a4a8a",
      "--input-text-color": "#87ceeb",
      "--button-primary-bg-color": "#4169e1",
      "--button-primary-hover-bg-color": "#6495ed",
      "--thumbnail-bg-color": "#0f1f35",
      "--thumbnail-grid-color": "rgba(65, 105, 225, 0.12)",
      "--thumbnail-main-text-color": "#87ceeb",
      "--thumbnail-secondary-text-color": "#4682b4",
    },
  },
  "ruby-fire": {
    name: "Ruby Fire",
    category: "Colorful",
    colors: {
      "--page-bg-color": "#2e0a0a",
      "--controls-bg-color": "#4a1a1a",
      "--input-bg-color": "#6a2a2a",
      "--input-border-color": "#8a3a3a",
      "--input-text-color": "#ffb6c1",
      "--button-primary-bg-color": "#dc143c",
      "--button-primary-hover-bg-color": "#ff1744",
      "--thumbnail-bg-color": "#350f0f",
      "--thumbnail-grid-color": "rgba(220, 20, 60, 0.12)",
      "--thumbnail-main-text-color": "#ffb6c1",
      "--thumbnail-secondary-text-color": "#ff6b6b",
    },
  },
  "amber-sunset": {
    name: "Amber Sunset",
    category: "Colorful",
    colors: {
      "--page-bg-color": "#2e1a0a",
      "--controls-bg-color": "#4a2a1a",
      "--input-bg-color": "#6a3a2a",
      "--input-border-color": "#8a4a3a",
      "--input-text-color": "#ffd700",
      "--button-primary-bg-color": "#ff8c00",
      "--button-primary-hover-bg-color": "#ffa500",
      "--thumbnail-bg-color": "#351f0f",
      "--thumbnail-grid-color": "rgba(255, 140, 0, 0.12)",
      "--thumbnail-main-text-color": "#ffd700",
      "--thumbnail-secondary-text-color": "#ffb347",
    },
  },
  "teal-ocean": {
    name: "Teal Ocean",
    category: "Colorful",
    colors: {
      "--page-bg-color": "#0a2e2e",
      "--controls-bg-color": "#1a4a4a",
      "--input-bg-color": "#2a6a6a",
      "--input-border-color": "#3a8a8a",
      "--input-text-color": "#afeeee",
      "--button-primary-bg-color": "#20b2aa",
      "--button-primary-hover-bg-color": "#40e0d0",
      "--thumbnail-bg-color": "#0f3535",
      "--thumbnail-grid-color": "rgba(32, 178, 170, 0.12)",
      "--thumbnail-main-text-color": "#afeeee",
      "--thumbnail-secondary-text-color": "#48d1cc",
    },
  },
  "magenta-neon": {
    name: "Magenta Neon",
    category: "Colorful",
    colors: {
      "--page-bg-color": "#2e0a2e",
      "--controls-bg-color": "#4a1a4a",
      "--input-bg-color": "#6a2a6a",
      "--input-border-color": "#8a3a8a",
      "--input-text-color": "#ff69b4",
      "--button-primary-bg-color": "#ff1493",
      "--button-primary-hover-bg-color": "#ff69b4",
      "--thumbnail-bg-color": "#350f35",
      "--thumbnail-grid-color": "rgba(255, 20, 147, 0.15)",
      "--thumbnail-main-text-color": "#ff69b4",
      "--thumbnail-secondary-text-color": "#ff1493",
    },
  },
  "copper-warm": {
    name: "Copper Warm",
    category: "Colorful",
    colors: {
      "--page-bg-color": "#2e1a0a",
      "--controls-bg-color": "#4a2a1a",
      "--input-bg-color": "#6a3a2a",
      "--input-border-color": "#8a4a3a",
      "--input-text-color": "#daa520",
      "--button-primary-bg-color": "#cd853f",
      "--button-primary-hover-bg-color": "#deb887",
      "--thumbnail-bg-color": "#351f0f",
      "--thumbnail-grid-color": "rgba(205, 133, 63, 0.12)",
      "--thumbnail-main-text-color": "#daa520",
      "--thumbnail-secondary-text-color": "#cd853f",
    },
  },
  "silver-metallic": {
    name: "Silver Metallic",
    category: "Dark",
    colors: {
      "--page-bg-color": "#1a1a1a",
      "--controls-bg-color": "#2a2a2a",
      "--input-bg-color": "#3a3a3a",
      "--input-border-color": "#4a4a4a",
      "--input-text-color": "#c0c0c0",
      "--button-primary-bg-color": "#808080",
      "--button-primary-hover-bg-color": "#a0a0a0",
      "--thumbnail-bg-color": "#0f0f0f",
      "--thumbnail-grid-color": "rgba(192, 192, 192, 0.08)",
      "--thumbnail-main-text-color": "#e0e0e0",
      "--thumbnail-secondary-text-color": "#a0a0a0",
    },
  },
  "bronze-classic": {
    name: "Bronze Classic",
    category: "Colorful",
    colors: {
      "--page-bg-color": "#2a1a0a",
      "--controls-bg-color": "#3a2a1a",
      "--input-bg-color": "#4a3a2a",
      "--input-border-color": "#5a4a3a",
      "--input-text-color": "#cd7f32",
      "--button-primary-bg-color": "#b8860b",
      "--button-primary-hover-bg-color": "#daa520",
      "--thumbnail-bg-color": "#2f1f0f",
      "--thumbnail-grid-color": "rgba(184, 134, 11, 0.12)",
      "--thumbnail-main-text-color": "#cd7f32",
      "--thumbnail-secondary-text-color": "#b8860b",
    },
  },
  "platinum-elegant": {
    name: "Platinum Elegant",
    category: "Dark",
    colors: {
      "--page-bg-color": "#0f0f0f",
      "--controls-bg-color": "#1f1f1f",
      "--input-bg-color": "#2f2f2f",
      "--input-border-color": "#3f3f3f",
      "--input-text-color": "#e5e4e2",
      "--button-primary-bg-color": "#8e8e8e",
      "--button-primary-hover-bg-color": "#a0a0a0",
      "--thumbnail-bg-color": "#0a0a0a",
      "--thumbnail-grid-color": "rgba(229, 228, 226, 0.06)",
      "--thumbnail-main-text-color": "#f5f5f5",
      "--thumbnail-secondary-text-color": "#c0c0c0",
    },
  },
  "jade-natural": {
    name: "Jade Natural",
    category: "Colorful",
    colors: {
      "--page-bg-color": "#0a2e1a",
      "--controls-bg-color": "#1a4a2a",
      "--input-bg-color": "#2a6a3a",
      "--input-border-color": "#3a8a4a",
      "--input-text-color": "#98fb98",
      "--button-primary-bg-color": "#00a86b",
      "--button-primary-hover-bg-color": "#00b377",
      "--thumbnail-bg-color": "#0f351f",
      "--thumbnail-grid-color": "rgba(0, 168, 107, 0.12)",
      "--thumbnail-main-text-color": "#98fb98",
      "--thumbnail-secondary-text-color": "#00a86b",
    },
  },
  "coral-reef": {
    name: "Coral Reef",
    category: "Colorful",
    colors: {
      "--page-bg-color": "#2e0a1a",
      "--controls-bg-color": "#4a1a2a",
      "--input-bg-color": "#6a2a3a",
      "--input-border-color": "#8a3a4a",
      "--input-text-color": "#ff7f50",
      "--button-primary-bg-color": "#ff6347",
      "--button-primary-hover-bg-color": "#ff4500",
      "--thumbnail-bg-color": "#350f1f",
      "--thumbnail-grid-color": "rgba(255, 127, 80, 0.12)",
      "--thumbnail-main-text-color": "#ff7f50",
      "--thumbnail-secondary-text-color": "#ff6347",
    },
  },
  "indigo-mystic": {
    name: "Indigo Mystic",
    category: "Colorful",
    colors: {
      "--page-bg-color": "#0a0a2e",
      "--controls-bg-color": "#1a1a4a",
      "--input-bg-color": "#2a2a6a",
      "--input-border-color": "#3a3a8a",
      "--input-text-color": "#4b0082",
      "--button-primary-bg-color": "#6a0dad",
      "--button-primary-hover-bg-color": "#8a2be2",
      "--thumbnail-bg-color": "#0f0f35",
      "--thumbnail-grid-color": "rgba(106, 13, 173, 0.15)",
      "--thumbnail-main-text-color": "#e6e6fa",
      "--thumbnail-secondary-text-color": "#9370db",
    },
  },
  "golden-royal": {
    name: "Golden Royal",
    category: "Colorful",
    colors: {
      "--page-bg-color": "#2e2a0a",
      "--controls-bg-color": "#4a461a",
      "--input-bg-color": "#6a662a",
      "--input-border-color": "#8a863a",
      "--input-text-color": "#ffd700",
      "--button-primary-bg-color": "#daa520",
      "--button-primary-hover-bg-color": "#ffd700",
      "--thumbnail-bg-color": "#35350f",
      "--thumbnail-grid-color": "rgba(218, 165, 32, 0.12)",
      "--thumbnail-main-text-color": "#ffd700",
      "--thumbnail-secondary-text-color": "#daa520",
    },
  },
};

export const defaultTheme = "default";
